services:
  database:
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: identity
      POSTGRES_USER: identity
      POSTGRES_DB: identity
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db-data: {}
  rabbitmq-data: {}