name: Build Go Application

on: [workflow_call]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Display Go version
        run: go version
      - name: Build
        run: make build
      - name: Unit Test
        run: make unit