name: Pull Request CI

on: [push]

jobs:
  Application:
    uses: amcheste/identity/.github/workflows/build-app.yml@init
  Integration:
    needs: Application
    uses: amcheste/identity/.github/workflows/integration-test.yml@init
  Acceptance:
    needs: Integration
    uses: amcheste/identity/.github/workflows/acceptance-test.yml@init
  Docker:
    needs: Acceptance
    uses: amcheste/identity/.github/workflows/build-docker.yml@init